kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: alertmanager
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: prometheus-server
