kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-volume3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: grafana
