apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: remo

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: api-keys
    files:
      - secret/api-keys
