apiVersion: v1
kind: Service
metadata:
  name: remo-exporter
  labels:
    app: remo-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9352
      protocol: TCP
      targetPort: 9352
  selector:
    app: remo-exporter
